import type { Friend } from './types';

export const defaultFriends: Friend[] = [
    {
        id: '1',
        name: 'Mads',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'Bedre end Rhianna',
        artist: 'Citibois',
        isSelected: true,
        color: '#FF6B6B',
    },
    {
        id: '2',
        name: 'Signe',
        songFile: 'https://open.spotify.com/track/3N9huFk2IceMSlKoZLaUsv?si=486b176704404679',
        songTitle: 'Boten Anna',
        artist: 'Basshunter',
        isSelected: true,
        color: '#A7D8DE',
    },
    {
        id: '3',
        name: 'Anna R',
        songFile: 'https://open.spotify.com/track/7JJa6W4aba4AjrZ59ehfTW?si=0514b4f05d7a410e',
        songTitle: 'Postman Per',
        artist: 'Postman Per',
        isSelected: true,
        color: '#FFB347',
    },
    {
        id: '4',
        name: 'Madde',
        songFile: 'https://open.spotify.com/track/4ho7syVEFjd1Iw46MGZljn?si=5f7be815f76a42ab',
        songTitle: 'No Stress',
        artist: 'Laurent Wolf',
        isSelected: true,
        color: '#9DE24F',
    },
    {
        id: '5',
        name: 'Nico',
        songFile: 'https://open.spotify.com/track/04bQwUsZXNj8iFPg67orvF?si=2e514f7f01054834',
        songTitle: 'Tsunami',
        artist: 'DVBBS & Borgeous',
        isSelected: true,
        color: '#C39BD3',
    },
    {
        id: '6',
        name: 'Mai',
        songFile: 'https://open.spotify.com/track/4sOX1nhpKwFWPvoMMExi3q?si=c91fc614e5b8447e',
        songTitle: 'Primadonna',
        artist: 'MARINA',
        isSelected: true,
        color: '#F7DC6F',
    },
    {
        id: '7',
        name: 'Anna B',
        songFile: 'https://open.spotify.com/track/5qaaQp6KvkEdB2q7SKQAcJ?si=097b401a2ec74738',
        songTitle: 'ErruDumEllaHvad',
        artist: 'ICEKIDD',
        isSelected: true,
        color: '#EC7063',
    },
    {
        id: '8',
        name: 'Bondo',
        songFile: 'https://open.spotify.com/track/5ZjFa8NE9MHKBPNefxIh88?si=517313ea687e4119',
        songTitle: 'Give it To Me - Sped Up',
        artist: 'FYLOW',
        isSelected: true,
        color: '#4ECDC4',
    },
    {
        id: '9',
        name: 'Astrid',
        songFile: 'https://open.spotify.com/track/3KDCYRQl4O681lkYI2sCqE?si=cddbaa1a58c84581',
        songTitle: 'Hey Mama',
        artist: 'Black Eyed Peas',
        isSelected: true,
        color: '#AED6F1',
    },
    {
        id: '10',
        name: 'Niller',
        songFile: 'https://open.spotify.com/track/3cHyrEgdyYRjgJKSOiOtcS?si=862de87cb3d543b6',
        songTitle: 'Timber',
        artist: 'Pitbull, Kesha',
        isSelected: true,
        color: '#F1948A',
    },
    {
        id: '11',
        name: 'Loui',
        songFile: 'https://open.spotify.com/track/3r9O77ImIXYKSLlw9YDoba?si=a1d01d9ce96a427f',
        songTitle: 'Big Booty Bitches',
        artist: 'A Lost People',
        isSelected: true,
        color: '#ABEBC6',
    },
    {
        id: '12',
        name: 'Katinka',
        songFile: 'https://open.spotify.com/track/0Dh9bAazKVfrHO34cMJpmU?si=093fadd11c854904',
        songTitle: 'Jeg Kommer',
        artist: 'Daimi',
        isSelected: true,
        color: '#D7BDE2',
    },
    {
        id: '13',
        name: 'Ada',
        songFile: 'https://open.spotify.com/track/3PzfAzqI03wcX8OikTdrH2?si=a6e0d20361054b2d',
        songTitle: 'Viva La Vida',
        artist: 'Soppgirobygget',
        isSelected: true,
        color: '#FAD7A0',
    },
];
