import type { Friend } from './types';

export const defaultFriends: Friend[] = [
    {
        id: '1',
        name: 'Mads',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'Bedre end Rhianna',
        artist: 'Citibois',
        isSelected: true,
        color: '#FF6B6B',
    },
    {
        id: '2',
        name: 'Signe',
        songFile: 'https://open.spotify.com/track/3N9huFk2IceMSlKoZLaUsv?si=486b176704404679',
        songTitle: 'Boten Anna',
        artist: 'Basshunter',
        isSelected: true,
        color: '#A7D8DE',
    },
    {
        id: '3',
        name: 'Anna R',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'Lovely',
        artist: 'Billie Eilish & Khalid',
        isSelected: true,
        color: '#FFB347',
    },
    {
        id: '4',
        name: 'Madde',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'Bad Habits',
        artist: 'Ed Sheeran',
        isSelected: true,
        color: '#9DE24F',
    },
    {
        id: '5',
        name: 'Nico',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'Blinding Lights',
        artist: 'The Weeknd',
        isSelected: true,
        color: '#C39BD3',
    },
    {
        id: '6',
        name: 'Mai',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'Shape of You',
        artist: 'Ed Sheeran',
        isSelected: true,
        color: '#F7DC6F',
    },
    {
        id: '7',
        name: 'Anna B',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'Levitating',
        artist: 'Dua Lipa',
        isSelected: true,
        color: '#EC7063',
    },
    {
        id: '8',
        name: 'Bondo',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'As It Was',
        artist: 'Harry Styles',
        isSelected: true,
        color: '#4ECDC4',
    },
    {
        id: '9',
        name: 'Astrid',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'As It Was',
        artist: 'Harry Styles',
        isSelected: true,
        color: '#AED6F1',
    },
    {
        id: '10',
        name: 'Niller',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'As It Was',
        artist: 'Harry Styles',
        isSelected: true,
        color: '#F1948A',
    },
    {
        id: '11',
        name: 'Loui',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'As It Was',
        artist: 'Harry Styles',
        isSelected: true,
        color: '#ABEBC6',
    },
    {
        id: '12',
        name: 'Katinka',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'As It Was',
        artist: 'Harry Styles',
        isSelected: true,
        color: '#D7BDE2',
    },
    {
        id: '13',
        name: 'Ada',
        songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
        songTitle: 'As It Was',
        artist: 'Harry Styles',
        isSelected: true,
        color: '#FAD7A0',
    },
];
