import type { Friend } from './types';

export const defaultFriends: Friend[] = [
  {
    id: '1',
    name: 'Mads',
    songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
    songTitle: 'Bedre end Rhianna',
    artist: 'Citibois',
    isSelected: true,
    color: '#FF6B6B',
  },
  {
    id: '2',
    name: 'Signe',
    songFile: 'https://open.spotify.com/track/3N9huFk2IceMSlKoZLaUsv?si=486b176704404679',
    songTitle: 'Boten Anna',
    artist: 'Basshunter',
    isSelected: true,
    color: '#4ECDC4',
  },
  {
    id: '3',
    name: 'Taylor',
    songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
    songTitle: 'Lovely',
    artist: 'Billie Eilish & Khalid',
    isSelected: true,
    color: '#45B7D1',
  },
  {
    id: '4',
    name: 'Morgan',
    songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
    songTitle: 'Bad Habits',
    artist: 'Ed Sheeran',
    isSelected: true,
    color: '#96CEB4',
  },
  {
    id: '5',
    name: 'Casey',
    songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
    songTitle: 'Blinding Lights',
    artist: 'The Weeknd',
    isSelected: true,
    color: '#FFEAA7',
  },
  {
    id: '6',
    name: 'Riley',
    songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
    songTitle: 'Shape of You',
    artist: 'Ed Sheeran',
    isSelected: true,
    color: '#DDA0DD',
  },
  {
    id: '7',
    name: 'Cameron',
    songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
    songTitle: 'Levitating',
    artist: 'Dua Lipa',
    isSelected: true,
    color: '#98D8C8',
  },
  {
    id: '8',
    name: 'Jamie',
    songFile: 'https://open.spotify.com/track/7ANC6AmXIoA7lqr6ebDWLz?si=26a6e38dd64a41ba',
    songTitle: 'As It Was',
    artist: 'Harry Styles',
    isSelected: true,
    color: '#F7DC6F',
  },
];
